
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA EQUALS LPAREN NAME NULL NUMBER NVL RPARENstatement : expressionexpression : LPAREN expression RPARENexpression : NUMBER COMMA NUMBER\n                  | NULL COMMA NUMBER\n    expression : NVL expressionexpression : NULL'
    
_lr_action_items = {'LPAREN':([0,3,6,],[3,3,3,]),'NUMBER':([0,3,6,8,9,],[4,4,4,12,13,]),'NULL':([0,3,6,],[5,5,5,]),'NVL':([0,3,6,],[6,6,6,]),'$end':([1,2,5,10,11,12,13,],[0,-1,-6,-5,-2,-3,-4,]),'COMMA':([4,5,],[8,9,]),'RPAREN':([5,7,10,11,12,13,],[-6,11,-5,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,6,],[2,7,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','decode.py',70),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','decode.py',74),
  ('expression -> NUMBER COMMA NUMBER','expression',3,'p_expression_decode','decode.py',78),
  ('expression -> NULL COMMA NUMBER','expression',3,'p_expression_decode','decode.py',79),
  ('expression -> NVL expression','expression',2,'p_expression_NVL','decode.py',84),
  ('expression -> NULL','expression',1,'p_expression_NULL','decode.py',88),
]
